version: 2.0.{build}
image: Visual Studio 2019
before_build:
- cmd: >-
    SET nugetbuildno=%APPVEYOR_BUILD_NUMBER%

    Echo %APPVEYOR_REPO_BRANCH%

    Echo %APPVEYOR_PULL_REQUEST_TITLE%

    SET nugetbuild=%nugetbuildno%-alpha

    IF %APPVEYOR_REPO_BRANCH% == develop SET nugetbuild=%nugetbuildno%-beta

    IF %APPVEYOR_REPO_BRANCH% == master SET nugetbuild=%nugetbuildno%

    IF NOT "%APPVEYOR_PULL_REQUEST_TITLE%" == "" SET nugetbuild=%nugetbuildno%-alpha

    Echo %nugetbuild%

    SET DOTNET_BUILD_VERSION=2.0.%nugetbuild%
